apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ratelimits.nginx.ratelimiter
spec:
  group: nginx.ratelimiter
  names:
    kind: RateLimits
    plural: ratelimits
    singular: ratelimits
    shortNames:
      - rls
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - selector
                - rateLimits
              properties:
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        required:
                          - key
                          - operator
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum: ["In", "NotIn", "Exists", "DoesNotExist"]
                          values:
                            type: array
                            items:
                              type: string
                env:
                  type: object
                  additionalProperties:
                    type: string
                rateLimits:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
