apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ratelimits.nginx.ratelimiter
spec:
  group: nginx.ratelimiter
  names:
    kind: RateLimits
    plural: ratelimits
    singular: ratelimits
    shortNames:
    - rls
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              env:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              rateLimits:
                type: object
                x-kubernetes-preserve-unknown-fields: true
