name: Release Charts

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Run Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: .cr.yaml
          charts_dir: manifests
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
