name: Release Charts

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .cr.yaml
          charts_dir: manifests
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
